// <auto-generated />
using System;
using InteresMe.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InteresMe.API.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260617065343_AddChatMessagingAreas")]
    partial class AddChatMessagingAreas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InteresMe.API.Modules.Auth.Models.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("refresh_tokens", "auth");
                });

            modelBuilder.Entity("InteresMe.API.Modules.Auth.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("GithubId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("GoogleId")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(72)
                        .HasColumnType("character varying(72)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("GithubId")
                        .IsUnique();

                    b.HasIndex("GoogleId")
                        .IsUnique();

                    b.ToTable("users", "auth");
                });

            modelBuilder.Entity("InteresMe.API.Modules.Chat.Channels.Models.Channel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("InitiativeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("InitiativeId");

                    b.ToTable("channels", "chat");
                });

            modelBuilder.Entity("InteresMe.API.Modules.Chat.Channels.Models.ChannelMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChannelId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("ChannelId", "UserId")
                        .IsUnique();

                    b.ToTable("channel_members", "chat");
                });

            modelBuilder.Entity("InteresMe.API.Modules.Chat.DirectMessages.Models.DirectConversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserOneId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserTwoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserTwoId");

                    b.HasIndex("UserOneId", "UserTwoId")
                        .IsUnique();

                    b.ToTable("direct_conversations", "chat");
                });

            modelBuilder.Entity("InteresMe.API.Modules.Chat.DirectMessages.Models.DirectConversationParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DirectConversationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("DirectConversationId", "UserId")
                        .IsUnique();

                    b.ToTable("direct_conversation_participants", "chat");
                });

            modelBuilder.Entity("InteresMe.API.Modules.Chat.Groups.Models.GroupChat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("InitiativeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("InitiativeId")
                        .IsUnique();

                    b.ToTable("group_chats", "chat");
                });

            modelBuilder.Entity("InteresMe.API.Modules.Chat.Groups.Models.GroupChatParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("GroupChatId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("GroupChatId", "UserId")
                        .IsUnique();

                    b.ToTable("group_chat_participants", "chat");
                });

            modelBuilder.Entity("InteresMe.API.Modules.Chat.Shared.Models.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ChannelId")
                        .HasColumnType("uuid");

                    b.Property<int>("ConversationType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DirectConversationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EditedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("GroupChatId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("SenderUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("SenderUserId");

                    b.HasIndex("ChannelId", "CreatedAt");

                    b.HasIndex("DirectConversationId", "CreatedAt");

                    b.HasIndex("GroupChatId", "CreatedAt");

                    b.ToTable("chat_messages", "chat", t =>
                        {
                            t.HasCheckConstraint("CK_chat_messages_single_conversation", "(\"ConversationType\" = 1 AND \"DirectConversationId\" IS NOT NULL AND \"GroupChatId\" IS NULL AND \"ChannelId\" IS NULL)\nOR (\"ConversationType\" = 2 AND \"DirectConversationId\" IS NULL AND \"GroupChatId\" IS NOT NULL AND \"ChannelId\" IS NULL)\nOR (\"ConversationType\" = 3 AND \"DirectConversationId\" IS NULL AND \"GroupChatId\" IS NULL AND \"ChannelId\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("InteresMe.API.Modules.Discovery.Models.UserDiscoveryPreference", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Goal")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId");

                    b.HasIndex("Goal");

                    b.ToTable("user_discovery_preferences", "discovery");
                });

            modelBuilder.Entity("InteresMe.API.Modules.Initiatives.Domain.Entities.Initiative", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GoalType")
                        .HasColumnType("integer");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int?>("TeamSize")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("University")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Visibility")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("GoalType");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.HasIndex("Visibility");

                    b.ToTable("initiatives", "initiatives");
                });

            modelBuilder.Entity("InteresMe.API.Modules.Initiatives.Domain.Entities.InitiativeInterest", b =>
                {
                    b.Property<Guid>("InitiativeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("InterestId")
                        .HasColumnType("uuid");

                    b.HasKey("InitiativeId", "InterestId");

                    b.HasIndex("InterestId");

                    b.ToTable("initiative_interests", "initiatives");
                });

            modelBuilder.Entity("InteresMe.API.Modules.Initiatives.Domain.Entities.InitiativeJoinRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Availability")
                        .HasColumnType("text");

                    b.Property<string>("Contribution")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Experience")
                        .HasColumnType("text");

                    b.Property<Guid>("InitiativeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Message")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Motivation")
                        .HasColumnType("text");

                    b.Property<Guid?>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("InitiativeId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("initiative_join_requests", "initiatives");
                });

            modelBuilder.Entity("InteresMe.API.Modules.Initiatives.Domain.Entities.InitiativeRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("InitiativeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("InitiativeId");

                    b.ToTable("initiative_roles", "initiatives");
                });

            modelBuilder.Entity("InteresMe.API.Modules.Interests.Models.Interest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("interests", "interests");
                });

            modelBuilder.Entity("InteresMe.API.Modules.Interests.Models.UserInterest", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("InterestId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "InterestId");

                    b.HasIndex("InterestId");

                    b.ToTable("user_interests", "interests");
                });

            modelBuilder.Entity("InteresMe.API.Modules.Profile.Models.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("Bio")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("City")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Headline")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("user_profiles", "profile");
                });

            modelBuilder.Entity("InteresMe.API.Modules.Verification.Models.UserVerification", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EmailVerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("IdentityVerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime?>("PhoneVerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TrustScore")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId");

                    b.ToTable("user_verifications", "verification");
                });

            modelBuilder.Entity("InteresMe.API.Modules.Verification.Models.VerificationToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Target")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash");

                    b.HasIndex("UserId");

                    b.ToTable("verification_tokens", "verification");
                });

            modelBuilder.Entity("InteresMe.API.Modules.Auth.Models.RefreshToken", b =>
                {
                    b.HasOne("InteresMe.API.Modules.Auth.Models.User", "user")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("InteresMe.API.Modules.Chat.Channels.Models.Channel", b =>
                {
                    b.HasOne("InteresMe.API.Modules.Initiatives.Domain.Entities.Initiative", "Initiative")
                        .WithMany()
                        .HasForeignKey("InitiativeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Initiative");
                });

            modelBuilder.Entity("InteresMe.API.Modules.Chat.Channels.Models.ChannelMember", b =>
                {
                    b.HasOne("InteresMe.API.Modules.Chat.Channels.Models.Channel", "Channel")
                        .WithMany("Members")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InteresMe.API.Modules.Auth.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Channel");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InteresMe.API.Modules.Chat.DirectMessages.Models.DirectConversation", b =>
                {
                    b.HasOne("InteresMe.API.Modules.Auth.Models.User", "UserOne")
                        .WithMany()
                        .HasForeignKey("UserOneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InteresMe.API.Modules.Auth.Models.User", "UserTwo")
                        .WithMany()
                        .HasForeignKey("UserTwoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UserOne");

                    b.Navigation("UserTwo");
                });

            modelBuilder.Entity("InteresMe.API.Modules.Chat.DirectMessages.Models.DirectConversationParticipant", b =>
                {
                    b.HasOne("InteresMe.API.Modules.Chat.DirectMessages.Models.DirectConversation", "DirectConversation")
                        .WithMany("Participants")
                        .HasForeignKey("DirectConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InteresMe.API.Modules.Auth.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DirectConversation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InteresMe.API.Modules.Chat.Groups.Models.GroupChat", b =>
                {
                    b.HasOne("InteresMe.API.Modules.Initiatives.Domain.Entities.Initiative", "Initiative")
                        .WithMany()
                        .HasForeignKey("InitiativeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Initiative");
                });

            modelBuilder.Entity("InteresMe.API.Modules.Chat.Groups.Models.GroupChatParticipant", b =>
                {
                    b.HasOne("InteresMe.API.Modules.Chat.Groups.Models.GroupChat", "GroupChat")
                        .WithMany("Participants")
                        .HasForeignKey("GroupChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InteresMe.API.Modules.Auth.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GroupChat");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InteresMe.API.Modules.Chat.Shared.Models.ChatMessage", b =>
                {
                    b.HasOne("InteresMe.API.Modules.Chat.Channels.Models.Channel", "Channel")
                        .WithMany("Messages")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("InteresMe.API.Modules.Chat.DirectMessages.Models.DirectConversation", "DirectConversation")
                        .WithMany("Messages")
                        .HasForeignKey("DirectConversationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("InteresMe.API.Modules.Chat.Groups.Models.GroupChat", "GroupChat")
                        .WithMany("Messages")
                        .HasForeignKey("GroupChatId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("InteresMe.API.Modules.Auth.Models.User", "SenderUser")
                        .WithMany()
                        .HasForeignKey("SenderUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Channel");

                    b.Navigation("DirectConversation");

                    b.Navigation("GroupChat");

                    b.Navigation("SenderUser");
                });

            modelBuilder.Entity("InteresMe.API.Modules.Discovery.Models.UserDiscoveryPreference", b =>
                {
                    b.HasOne("InteresMe.API.Modules.Auth.Models.User", "User")
                        .WithOne()
                        .HasForeignKey("InteresMe.API.Modules.Discovery.Models.UserDiscoveryPreference", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("InteresMe.API.Modules.Initiatives.Domain.Entities.Initiative", b =>
                {
                    b.HasOne("InteresMe.API.Modules.Auth.Models.User", "OwnerUser")
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OwnerUser");
                });

            modelBuilder.Entity("InteresMe.API.Modules.Initiatives.Domain.Entities.InitiativeInterest", b =>
                {
                    b.HasOne("InteresMe.API.Modules.Initiatives.Domain.Entities.Initiative", "Initiative")
                        .WithMany("InitiativeInterests")
                        .HasForeignKey("InitiativeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InteresMe.API.Modules.Interests.Models.Interest", "Interest")
                        .WithMany()
                        .HasForeignKey("InterestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Initiative");

                    b.Navigation("Interest");
                });

            modelBuilder.Entity("InteresMe.API.Modules.Initiatives.Domain.Entities.InitiativeJoinRequest", b =>
                {
                    b.HasOne("InteresMe.API.Modules.Initiatives.Domain.Entities.Initiative", "Initiative")
                        .WithMany("JoinRequests")
                        .HasForeignKey("InitiativeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InteresMe.API.Modules.Initiatives.Domain.Entities.InitiativeRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("InteresMe.API.Modules.Auth.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Initiative");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InteresMe.API.Modules.Initiatives.Domain.Entities.InitiativeRole", b =>
                {
                    b.HasOne("InteresMe.API.Modules.Initiatives.Domain.Entities.Initiative", "Initiative")
                        .WithMany("Roles")
                        .HasForeignKey("InitiativeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Initiative");
                });

            modelBuilder.Entity("InteresMe.API.Modules.Interests.Models.UserInterest", b =>
                {
                    b.HasOne("InteresMe.API.Modules.Interests.Models.Interest", "Interest")
                        .WithMany("UserInterests")
                        .HasForeignKey("InterestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InteresMe.API.Modules.Auth.Models.User", "User")
                        .WithMany("UserInterests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Interest");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InteresMe.API.Modules.Profile.Models.UserProfile", b =>
                {
                    b.HasOne("InteresMe.API.Modules.Auth.Models.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("InteresMe.API.Modules.Profile.Models.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("InteresMe.API.Modules.Verification.Models.UserVerification", b =>
                {
                    b.HasOne("InteresMe.API.Modules.Auth.Models.User", "User")
                        .WithOne()
                        .HasForeignKey("InteresMe.API.Modules.Verification.Models.UserVerification", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("InteresMe.API.Modules.Verification.Models.VerificationToken", b =>
                {
                    b.HasOne("InteresMe.API.Modules.Auth.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("InteresMe.API.Modules.Auth.Models.User", b =>
                {
                    b.Navigation("Profile");

                    b.Navigation("RefreshTokens");

                    b.Navigation("UserInterests");
                });

            modelBuilder.Entity("InteresMe.API.Modules.Chat.Channels.Models.Channel", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("InteresMe.API.Modules.Chat.DirectMessages.Models.DirectConversation", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("InteresMe.API.Modules.Chat.Groups.Models.GroupChat", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("InteresMe.API.Modules.Initiatives.Domain.Entities.Initiative", b =>
                {
                    b.Navigation("InitiativeInterests");

                    b.Navigation("JoinRequests");

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("InteresMe.API.Modules.Interests.Models.Interest", b =>
                {
                    b.Navigation("UserInterests");
                });
#pragma warning restore 612, 618
        }
    }
}
