export const APP_ROUTES = {
  auth: 'auth',
  login: 'auth/login',
  register: 'auth/register',
  callback: 'auth/callback',
  profile: 'profile',
  publicInitiative: 'i/:slug',
  initiatives: 'initiatives',
  initiativeCreate: 'initiatives/new',
  initiativeDetails: 'initiatives/:id',
  initiativeApply: 'initiatives/:id/apply',
  initiativeApplications: 'initiatives/:id/applications',
  initiativeEdit: 'initiatives/:id/edit',
  myInitiatives: 'me/initiatives',
  matches: 'matches',
  chat: 'chat',
} as const;
