export const APP_ROUTES = {
  auth: 'auth',
  login: 'auth/login',
  register: 'auth/register',
  callback: 'auth/callback',
  home: 'home',
  onboarding: 'onboarding',
  onboardingInterests: 'onboarding/interests',
  onboardingLoading: 'onboarding/loading',
  onboardingHope: 'onboarding/hope',
  profile: 'profile',
  publicInitiative: 'i/:slug',
  interests: 'interests',
  initiatives: 'initiatives',
  initiativeCreate: 'initiatives/new',
  initiativeDetails: 'initiatives/:id',
  initiativeApply: 'initiatives/:id/apply',
  initiativeApplications: 'initiatives/:id/applications',
  initiativeEdit: 'initiatives/:id/edit',
  myInitiatives: 'me/initiatives',
  matches: 'matches',
  chat: 'chats',
  settings: 'settings',
} as const;
