import { Interest, InterestCategory, Subinterest } from '../models/interest.model';

type InterestSeed = Pick<
  Interest,
  'id' | 'categoryId' | 'name' | 'slug' | 'description' | 'icon' | 'color' | 'peopleCount' | 'initiativesCount' | 'portfolioCount'
> & {
  subinterestNames: string[];
};

const createSubinterests = (interestId: string, names: string[]): Subinterest[] =>
  names.map((name, index) => ({
    id: `${interestId}-${name.toLowerCase().replace(/[^a-z0-9]+/g, '-')}`,
    interestId,
    name,
    slug: name.toLowerCase().replace(/[^a-z0-9]+/g, '-'),
    peopleCount: 70 + index * 24,
    initiativesCount: 5 + index * 3,
    portfolioCount: 12 + index * 8,
  }));

const createInterest = (seed: InterestSeed): Interest => ({
  ...seed,
  subinterests: createSubinterests(seed.id, seed.subinterestNames),
});

export const MOCK_INTEREST_CATEGORIES: InterestCategory[] = [
  {
    id: 'create',
    name: 'Create',
    slug: 'create',
    description: 'Creative work, visual arts, music, writing, media and expression.',
    icon: 'CR',
    color: '#fb6f61',
    peopleCount: 3490,
    initiativesCount: 197,
    portfolioCount: 919,
    interests: [
      createInterest({
        id: 'design',
        categoryId: 'create',
        name: 'Design',
        slug: 'design',
        description: 'Shape visuals, interfaces and product experiences.',
        icon: 'DS',
        color: '#fb6f61',
        peopleCount: 860,
        initiativesCount: 48,
        portfolioCount: 244,
        subinterestNames: ['UI/UX Design', 'Graphic Design', 'Motion Design', 'Product Design'],
      }),
      createInterest({
        id: 'music',
        categoryId: 'create',
        name: 'Music',
        slug: 'music',
        description: 'Play, write, produce and perform with other people.',
        icon: 'MS',
        color: '#f59e0b',
        peopleCount: 920,
        initiativesCount: 55,
        portfolioCount: 188,
        subinterestNames: ['Guitar', 'Piano', 'Vocals', 'Production'],
      }),
      createInterest({
        id: 'photography',
        categoryId: 'create',
        name: 'Photography',
        slug: 'photography',
        description: 'Plan shoots, edit images and tell visual stories.',
        icon: 'PH',
        color: '#38bdf8',
        peopleCount: 540,
        initiativesCount: 27,
        portfolioCount: 172,
        subinterestNames: ['Portrait', 'Street Photography', 'Editing', 'Visual Storytelling'],
      }),
      createInterest({
        id: 'cinema',
        categoryId: 'create',
        name: 'Cinema',
        slug: 'cinema',
        description: 'Make films, write scenes and gather creative crews.',
        icon: 'CN',
        color: '#ef4444',
        peopleCount: 410,
        initiativesCount: 24,
        portfolioCount: 89,
        subinterestNames: ['Filmmaking', 'Screenwriting', 'Editing', 'Acting'],
      }),
      createInterest({
        id: 'art',
        categoryId: 'create',
        name: 'Art',
        slug: 'art',
        description: 'Draw, paint, explore concepts and share creative practice.',
        icon: 'AR',
        color: '#a855f7',
        peopleCount: 760,
        initiativesCount: 43,
        portfolioCount: 226,
        subinterestNames: ['Illustration', 'Digital Art', 'Painting', 'Concept Art'],
      }),
    ],
  },
  {
    id: 'build',
    name: 'Build',
    slug: 'build',
    description: 'Technology, programming, engineering, startups and product creation.',
    icon: 'BD',
    color: '#14b8a6',
    peopleCount: 3830,
    initiativesCount: 216,
    portfolioCount: 806,
    interests: [
      createInterest({
        id: 'programming',
        categoryId: 'build',
        name: 'Programming',
        slug: 'programming',
        description: 'Build apps, tools, systems, games and experiments with code.',
        icon: '</>',
        color: '#14b8a6',
        peopleCount: 1280,
        initiativesCount: 74,
        portfolioCount: 312,
        subinterestNames: ['Backend', 'Frontend', 'GameDev', 'AI', 'DevOps'],
      }),
      createInterest({
        id: 'startups',
        categoryId: 'build',
        name: 'Startups',
        slug: 'startups',
        description: 'Turn ideas into early products, teams and experiments.',
        icon: 'SU',
        color: '#38bdf8',
        peopleCount: 690,
        initiativesCount: 39,
        portfolioCount: 124,
        subinterestNames: ['SaaS', 'Marketplace', 'Mobile App', 'Student Startup'],
      }),
      createInterest({
        id: 'engineering',
        categoryId: 'build',
        name: 'Engineering',
        slug: 'engineering',
        description: 'Prototype physical systems, devices and technical ideas.',
        icon: 'EN',
        color: '#64748b',
        peopleCount: 520,
        initiativesCount: 31,
        portfolioCount: 91,
        subinterestNames: ['Electronics', 'Mechanics', '3D Printing', 'Prototyping'],
      }),
      createInterest({
        id: 'robotics',
        categoryId: 'build',
        name: 'Robotics',
        slug: 'robotics',
        description: 'Create machines, drones, automation and sensor projects.',
        icon: 'RB',
        color: '#0ea5e9',
        peopleCount: 430,
        initiativesCount: 26,
        portfolioCount: 83,
        subinterestNames: ['Arduino', 'Drones', 'Automation', 'Sensors'],
      }),
      createInterest({
        id: 'product',
        categoryId: 'build',
        name: 'Product',
        slug: 'product',
        description: 'Connect user problems, product decisions and outcomes.',
        icon: 'PD',
        color: '#22c55e',
        peopleCount: 910,
        initiativesCount: 46,
        portfolioCount: 196,
        subinterestNames: ['Product Management', 'Product Design', 'Analytics', 'User Research'],
      }),
    ],
  },
  {
    id: 'learn',
    name: 'Learn',
    slug: 'learn',
    description: 'Science, languages, education, research, books and self-development.',
    icon: 'LR',
    color: '#8b5cf6',
    peopleCount: 3050,
    initiativesCount: 174,
    portfolioCount: 555,
    interests: [
      createInterest({
        id: 'science',
        categoryId: 'learn',
        name: 'Science',
        slug: 'science',
        description: 'Explore research, experiments and curious discussions.',
        icon: 'SC',
        color: '#0ea5e9',
        peopleCount: 580,
        initiativesCount: 34,
        portfolioCount: 97,
        subinterestNames: ['Physics', 'Biology', 'Chemistry', 'Astronomy'],
      }),
      createInterest({
        id: 'languages',
        categoryId: 'learn',
        name: 'Languages',
        slug: 'languages',
        description: 'Practice speaking, writing and learning with others.',
        icon: 'LA',
        color: '#8b5cf6',
        peopleCount: 760,
        initiativesCount: 44,
        portfolioCount: 112,
        subinterestNames: ['English', 'German', 'Polish', 'Spanish'],
      }),
      createInterest({
        id: 'education',
        categoryId: 'learn',
        name: 'Education',
        slug: 'education',
        description: 'Study together, prepare for exams and share knowledge.',
        icon: 'ED',
        color: '#14b8a6',
        peopleCount: 640,
        initiativesCount: 39,
        portfolioCount: 91,
        subinterestNames: ['Tutoring', 'Study Groups', 'Exams', 'Courses'],
      }),
      createInterest({
        id: 'books',
        categoryId: 'learn',
        name: 'Books',
        slug: 'books',
        description: 'Read, discuss ideas and build reading communities.',
        icon: 'BK',
        color: '#f59e0b',
        peopleCount: 520,
        initiativesCount: 28,
        portfolioCount: 143,
        subinterestNames: ['Fiction', 'Non-fiction', 'Philosophy', 'Psychology'],
      }),
      createInterest({
        id: 'research',
        categoryId: 'learn',
        name: 'Research',
        slug: 'research',
        description: 'Work on papers, analysis, experiments and reports.',
        icon: 'RS',
        color: '#38bdf8',
        peopleCount: 550,
        initiativesCount: 29,
        portfolioCount: 112,
        subinterestNames: ['Academic Research', 'Data Analysis', 'Experiments', 'Reports'],
      }),
    ],
  },
  {
    id: 'move',
    name: 'Move',
    slug: 'move',
    description: 'Sport, dance, travel, outdoor activities and physical challenges.',
    icon: 'MV',
    color: '#22c55e',
    peopleCount: 3350,
    initiativesCount: 188,
    portfolioCount: 367,
    interests: [
      createInterest({
        id: 'sport',
        categoryId: 'move',
        name: 'Sport',
        slug: 'sport',
        description: 'Find teams, training partners, games and active communities.',
        icon: 'SP',
        color: '#22c55e',
        peopleCount: 1030,
        initiativesCount: 61,
        portfolioCount: 74,
        subinterestNames: ['Gym', 'Football', 'Basketball', 'Running'],
      }),
      createInterest({
        id: 'dance',
        categoryId: 'move',
        name: 'Dance',
        slug: 'dance',
        description: 'Practice movement, choreography and performance.',
        icon: 'DN',
        color: '#ec4899',
        peopleCount: 480,
        initiativesCount: 27,
        portfolioCount: 82,
        subinterestNames: ['Hip-Hop', 'Contemporary', 'Ballroom', 'Choreography'],
      }),
      createInterest({
        id: 'travel',
        categoryId: 'move',
        name: 'Travel',
        slug: 'travel',
        description: 'Discover places, routes and cultural experiences together.',
        icon: 'TR',
        color: '#38bdf8',
        peopleCount: 760,
        initiativesCount: 42,
        portfolioCount: 96,
        subinterestNames: ['City Walks', 'Hiking', 'Backpacking', 'Cultural Trips'],
      }),
      createInterest({
        id: 'outdoor',
        categoryId: 'move',
        name: 'Outdoor',
        slug: 'outdoor',
        description: 'Plan active days outside and try new physical challenges.',
        icon: 'OD',
        color: '#16a34a',
        peopleCount: 520,
        initiativesCount: 31,
        portfolioCount: 57,
        subinterestNames: ['Camping', 'Cycling', 'Climbing', 'Kayaking'],
      }),
      createInterest({
        id: 'lifestyle',
        categoryId: 'move',
        name: 'Lifestyle',
        slug: 'lifestyle',
        description: 'Build habits, routines and personal challenges.',
        icon: 'LF',
        color: '#f59e0b',
        peopleCount: 560,
        initiativesCount: 27,
        portfolioCount: 58,
        subinterestNames: ['Nutrition', 'Discipline', 'Morning Routine', 'Challenges'],
      }),
    ],
  },
  {
    id: 'impact',
    name: 'Impact',
    slug: 'impact',
    description: 'Volunteering, communities, business, ecology and social initiatives.',
    icon: 'IM',
    color: '#f59e0b',
    peopleCount: 3190,
    initiativesCount: 183,
    portfolioCount: 453,
    interests: [
      createInterest({
        id: 'volunteering',
        categoryId: 'impact',
        name: 'Volunteering',
        slug: 'volunteering',
        description: 'Help people, events and causes through practical action.',
        icon: 'VL',
        color: '#22c55e',
        peopleCount: 740,
        initiativesCount: 47,
        portfolioCount: 96,
        subinterestNames: ['Charity', 'Animal Help', 'Event Help', 'Fundraising'],
      }),
      createInterest({
        id: 'community',
        categoryId: 'impact',
        name: 'Community',
        slug: 'community',
        description: 'Create spaces where people can meet, support and organize.',
        icon: 'CM',
        color: '#14b8a6',
        peopleCount: 680,
        initiativesCount: 39,
        portfolioCount: 84,
        subinterestNames: ['Student Clubs', 'Local Communities', 'Online Communities', 'Events'],
      }),
      createInterest({
        id: 'business',
        categoryId: 'impact',
        name: 'Business',
        slug: 'business',
        description: 'Learn markets, sales, finance and entrepreneurship.',
        icon: 'BZ',
        color: '#f59e0b',
        peopleCount: 690,
        initiativesCount: 39,
        portfolioCount: 124,
        subinterestNames: ['Marketing', 'Sales', 'Finance', 'Entrepreneurship'],
      }),
      createInterest({
        id: 'ecology',
        categoryId: 'impact',
        name: 'Ecology',
        slug: 'ecology',
        description: 'Work on cleaner habits, climate awareness and local action.',
        icon: 'EC',
        color: '#16a34a',
        peopleCount: 480,
        initiativesCount: 28,
        portfolioCount: 62,
        subinterestNames: ['Recycling', 'Cleanups', 'Climate', 'Sustainable Living'],
      }),
      createInterest({
        id: 'social-projects',
        categoryId: 'impact',
        name: 'Social Projects',
        slug: 'social-projects',
        description: 'Build initiatives around inclusion, access and youth support.',
        icon: 'SO',
        color: '#ef4444',
        peopleCount: 600,
        initiativesCount: 30,
        portfolioCount: 87,
        subinterestNames: ['Education Access', 'Mental Health Awareness', 'Inclusion', 'Youth Projects'],
      }),
    ],
  },
];
