name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  backend:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore backend
        run: dotnet restore
        working-directory: ./InteresMe.API

      - name: Build backend
        run: dotnet build --no-restore
        working-directory: ./InteresMe.API

  frontend:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install frontend dependencies
        run: npm install
        working-directory: ./InteresMe.Client

      - name: Build frontend
        run: npm run build
        working-directory: ./InteresMe.Client